export enum RoutesPaths {
  any = '*',
  root = '/',
  backend = '/backend',
  static = '/static',
  images = '/images',
  home = '/home',
  signIn = '/sign-in',
  signUp = '/sign-up',
  catalog = '/catalog',
  profile = '/profile',
  comments = '/comments',
  getAll = '/get-all',
  addOne = '/add-one',
  deleteOne = '/delete-one',
  clientMenu = '/menu/client',
  courierMenu = '/menu/courier',
  managerMenu = '/menu/manager',
  getOrders = '/get-orders',
  declineOrder = '/decline-order',
}
